### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by joaopcnogueira** [solegalli/feature_engine#1]
Hello there!

Firstly, I really would like to thank you for providing this package. Its really boosted my productivity!

Do you have plans for add new features? I felt the missing of scalers, for example.

Edit: Today I have written one function to do the MinMaxScaler and made a PR (https://github.com/solegalli/feature_engine/pull/2) @solegalli

**Comment by solegalli** [comment]
Hi @joaopcnogueira 

Glad you are enjoying the package. Over the next few months I will continue adding new features, so keep an eye on it, and make PRs if you find something useful.

Regarding the columns for the MinMaxScaler:
In the new version of sklearn, released dec last year, they added an object called ColumnTransformer, that allows to select columns for pretty much all the transformers, including the scalers I believe. Did you check it out? It is still in beta, but worth to try. I will include it as part of the feature engineering udemy course in the coming weeks, so if you are enrolled, you'll be able to see how to use it :)

Cheers

**Comment by joaopcnogueira** [comment]
I have used ColumnTransformer and it has worked fine! Good that you will include it as part of the feature engineering udemy course. I am enrolled and already following the updates you are making, great ones!
