### ISSUE TITLE
add check for NA in variable transformers

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#10]
All variable transformers should check if data set contains NA before training or transforming the data

**Comment by dehiker** [comment]
Hmm, could some transformers work with missing values, maybe simply ignore it?

**Comment by solegalli** [comment]
I think this is a very valuable safety measure for users, who may inadvertedly introduce NA in their datasets during manipulation, and without a warning or an error, they would carry the NA all the way to the prediction algorithm.

All transformers except the outlier transformers should have this check.
