### ISSUE TITLE
feature_selection: remove constant and quasiconstant features

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#113]
constant feature: only shows 1 value in all observations
quasi_constant feature: most values are the same.

Main code:

```
constant_features = [
    feat for feat in X_train.columns if X_train[feat].nunique() == 1
]
```

```
quasi_constant_feat = []
for feature in X_train.columns:

    # find the predominant value
    predominant = (X_train[feature].value_counts() / np.float(
        len(X_train))).sort_values(ascending=False).values[0]

    # evaluate predominant feature
    if predominant > 0.998:
        quasi_constant_feat.append(feature)

len(quasi_constant_feat)
```

**Comment by Tejash-Shah** [comment]
Hi @solegalli,

I was curious about the [DropFeatures class](https://github.com/solegalli/feature_engine/blob/045eb14f14b359b5bbbc100bd71573abe6f2a5b3/feature_engine/feature_selection.py#L7) in [feature_selection.py](https://github.com/solegalli/feature_engine/blob/master/feature_engine/feature_selection.py) and I was wondering what is the purpose of this class? Looking at the code it looks like it just drops the features as provided to ```features_to_drop``` argument and feels like a wrapper around ```df.drop()```. 

Is it work in progress? Do you have any plans to add constant_feature and quasi_constant functionality to this package? 

Thanks, 
Tejash

**Comment by solegalli** [comment]
Hi @Tejash-Shah 

Yes, that is the function of drop features. And yes, I want to include functionality to drop constant and quasi-constant features. Would you like to give it a go at trying to make this transformer?

**Comment by Tejash-Shah** [comment]
Sure, would be happy to contribute:) I can create a Transformer class based on TransformerMixin, with two attributes, ```constant_features_``` and ```non_constant_features_```. In that way it is scikit-learn compatible. However, we would be missing ```get_support()``` functionality which comes from ```SelectorMixin```. Any idea what functionality we would perhaps miss if we inherit ```TransformerMixin``` and not ```SelectorMixin``` . I think ```get_support()``` could be replaced by ```constant_features_``` and ```non_constant_features_``` attributes?

**Comment by solegalli** [comment]
Yes, I thought we should include the get_support() method to keep it similar to sklearn selectors. 

I can see that by inheriting the selectorMixin, the class would be inheriting the get_support() and transform functionality (https://github.com/scikit-learn/scikit-learn/blob/0fb307bf3/sklearn/feature_selection/_base.py#L17). And then, in the new selector, we would only have to write the _get_support_mask() method (eg: https://github.com/scikit-learn/scikit-learn/blob/0fb307bf3/sklearn/feature_selection/_univariate_selection.py#L460). This way, we keep the transformer compatible / more similar with sklearn.

I think that for this particular selector (constant, quasi-constant), it could work well. We could also add the attributes constant_features_ and non_constant_features_ as you suggest. I like it.

Users should be able to indicate as argument if they want to detect constant only, or constant and quasi-constant, with a threshold when initialising the class (1 for constant, or 0.99 for example for quasi-constant)

Thank you! @Tejash-Shah

**Comment by Tejash-Shah** [comment]
Thanks, @solegalli for the points. Will work on it and when I'm ready I will create a PR to review.

**Comment by solegalli** [comment]
Actually, after further thought, I think using sklearn's SelectorMixin is not such a good idea. Because sklearn returns numpy array, and feature-engine returns dataframes. So we would have to include more boilerplate code to transform the array into a dataframe, just so that we have the get_support funtionality.

I think it would be better to continue like with the other transformers of Feature engine, inherit only the Base and TransformerMixin, and write our own functionality. 

I think all selector features should have an attribute called selected_features_ with the features that will be retained. And for this particular case, also the attributes constant_features_ and non_constant_features_ as you suggest.

If you make a PR with a draft of the code, we can take it from there.

**Comment by Tejash-Shah** [comment]
Sure, that sounds good. 

I have my draft almost ready. Somewhat it looks like below. 

Code by default, finds and drops all constant features. Just like ```VarianceThreshold()```

Class has four attributes: 
1. ```constant_features_``` : available as soon as fit is called
2. ```non_constant_features_```: available as soon as fit is called
3. ```quasi_constant_features_```: available if ```drop_quasi_constant_features``` is set to True(by default False & by default quasi_constant_threshold=1); if not empty list
4.  ```non_quasi_constant_features_```: available if ```drop_quasi_constant_features``` is set to True; if not empty list
5. ```total_features_```: this is not added yet, just a thought so user knows what transformer is learning or it could turn out to be extra attribute which is really not needed...

Will create a PR as soon as I'm done writing test suites. Let me know if you want to add/remove something :) Thanks!

**Comment by solegalli** [comment]
Sounds good thanks! 

I would keep 1 and 3. And put together 2 and 4 into 1 attribute called `selected_features_`. Then, we could use this attribute in the transform method.

5  is not needed as it would be retained, somehow, in the attribute "shape_" that we should always return in fit to check if the size of the input dataframe in the transform matches the one of the training set.

Look forward to the PR.
Cheers
Sole

**Comment by solegalli** [comment]
#116 closed with this PR
