### ISSUE TITLE
feature selection: recursive feature elimination

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#134]
A transformer that implements this for various algorithms:

https://github.com/solegalli/feature-selection-for-machine-learning/blob/master/11-Hybrid-methods/11.2-Recursive-feature-elimination.ipynb

Should be able to use ML algos that output some sort of importance value, like coef_ or feature_importance_

**Comment by solegalli** [comment]
Hey @SunnyxBd 

If you had fun creating the shuffle feature selector and could spare a bit more of your valuable time, would you fancy trying to create this transformer?

Logic is as follows:

trains a model that has feature_importance or coeffs attributes (we need to check this with the hasattributes or something like this). It uses all features to train this model.

stores initial performance

Derives feature importance

Orders features from least to most important

Starting from the least important feature, removes feature, trains new model, determines importance, if importance smaller than initial importance beyond a threshold, keep feature, otherwise remove. Continue with next feature. Please have a look at the notebook to understand the logic a bit better.

It is somewhat similar to shuffle features.

The only thing I have not thought well yet is how to include cross_validation with cross_validate instead of splitting data into train and test as I do in the notebook. I think cross_validation is better. Not sure it is possible. 

Thank you!

**Comment by SunnyxBd** [comment]
This sound fun! @solegalli 

I'll start working on it soon and create an early PR so we can discuss progress similarly to the ShuffleFeatureSelector issue.

Cheers,
Sana

**Comment by SunnyxBd** [comment]
@solegalli 

I started working on this issue.

For the feature importance part with cross_validation, here's one method for getting the feature importance list 

let's say cv = 3.
We will have three models.
Eah model has its own feature importance
let's say:
model1 has [f1,f2,f3]
model2 has [f2,f1,f3]
model3 has [f1,f2,f3]

One way of selecting an aggregated ordered list of feature importance is to give each feature a score and use the score to order the final list.

 
for example:

model1 has [f1,f2,f3] == > f1's score is 3, f2's score is 2 , f3's score is 1
model2 has [f2,f1,f3] ==> f2's score is 3 , f1's score is 2 etc
model3 has [f1,f2,f3]

so a final scoring system would give f1 score = 8 , f2 score = 7 ,f3 score = 3

And the aggregated feature importance used for the initial model would be [f1,f2,f3]

Thoughts?

**Comment by solegalli** [comment]
Not too sure I follow the logic. Can we not get the mean importance of eacf feature by the 3 models?
If we capture importance in a pandas series, then we can concatenate the series in a dataframe, and get the mean importance per feature. And we order using that? 

Is this what you are suggesting?
Cheers
