### ISSUE TITLE
feature_selection: recursive feature addition

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#135]
A transformer with an implementation of this:

https://github.com/solegalli/feature-selection-for-machine-learning/blob/master/11-Hybrid-methods/11.3-Recursive-feature-addition.ipynb

Should be able to take algorithms that output some sort of measure of importance. We need to discuss how best to implement the stop criteria,

**Comment by solegalli** [comment]
@SunnyxBd if you are interested and could spare some time, it would be great to have you on board for this one.

It is very similar to the recursive feature elimination you created, but it goes the other way around:

- sorts feature from most important to least important
- trains a model with the most important feature (just the one feature)
- recursively adds features and selects them if the increase in performance is beyond a threshold

easy peasy for you :) 

No worries if out of time

Thanks a lot for your contrbutions

**Comment by SunnyxBd** [comment]
Hey @solegalli

Thank you for this suggestion.
I was going to ask what to work on next! 

I have some deadlines to finish this week which is why I can't promise I'll time this week.

I'll start working on this one next week, if that is alright with you.
I should be able to finish it quickly also.

**Comment by solegalli** [comment]
That is wonderful news @SunnyxBd thank you so much. 

Would you like me to add you as a contributor to the repo? this way you wont need to work over fork and can push directly here.

Master and deployment branches are protected, so no risk there. Only thing, never to merge without having someone review and approve the changes first.

Let me know.

Cheers
Sole

**Comment by SunnyxBd** [comment]
Please do, this is amazing. @solegalli 
And thank you a lot for your trust and guidance throughout this journey.

**Comment by solegalli** [comment]
Likewise!
