### ISSUE TITLE
separate Woe encoder into Woe encoder and Ratio encoder

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#143]
In short, WoE encoder should have only WoE functionality, And the probability ratio encoder should be in a separate transformer.

They are different concepts in my opinion.

**Comment by NicoGalli** [comment]
Sole, would you please assign this one to me? I would like to give it a try! Thanks. N.-

**Comment by solegalli** [comment]
With pleasure :)

One thing to notice, we are currently refactoring the code (quite massively), so please **check out the develop branch** and make the PR to that branch as well which contains the latest view :)

Suggestions:
1) RatioEncoder should go in a dedicated .py script.

2) Test should be divided into those for WoE and those for Ratio, the ones for Ratio in a separate script. And since we are improving this, maybe separate every test case into a single test as we do [here](https://github.com/solegalli/feature_engine/blob/master/tests/test_wrappers.py)(at the moment they are altogether in 1 function)

3) we need amend the docs accordingly. Files that need changing are docs/index.rst; encoders/index.rst and within the docs/encoders folder, remove the details on ratio in the WoE rst and create a ratioencoder rst 

Thank you! I look forward to the PR
