### ISSUE TITLE
function _define_variables should take only str or list of str

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#146]
Current implementation can take list of tuples, this behaviour should not be allowed. Should expand the test to catch this up.

**Comment by solegalli** [comment]
@Okroshiashvili ? could you take care of this one as part of the type hint PR?

**Comment by Okroshiashvili** [comment]
@solegalli I will take care of it

**Comment by Okroshiashvili** [comment]
Please, refer to the PR #159
