### ISSUE TITLE
replace listcomp with genexp in discretisation tests

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#150]
in test_equal_frequency_discretisation.py
in test_equal_width_discretisation.py

**Comment by solegalli** [comment]
@NicoGalli este es facil

**Comment by Okroshiashvili** [comment]
If you are not in rush, I'd like to handle this issue. Moreover, I will add some extra test cases.
@solegalli

**Comment by solegalli** [comment]
@Okroshiashvili awesome, Thanks

**Comment by Okroshiashvili** [comment]
See PR #164

**Comment by solegalli** [comment]
closed in #164
