### ISSUE TITLE
roll out type hint

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#152]
it might be beneficial to take advantage of Feature-Engine's relatively small code base to do it whilst it's still not so much work.

I'd suggest a gradual rollout in the following ways:

- Add a new circleci job for the typehints, and make it optional for merging prs

- Configure mypy to run against a subset of files at first (e.g. not the tests, example from [FastAPI](https://github.com/tiangolo/fastapi/blob/master/scripts/lint.sh#L6))

- Configure mypy to have some more relaxed rules in certain areas (example from [FastAPI](https://github.com/tiangolo/fastapi/blob/master/mypy.ini#L1))

Further down the line we might consider adding [precommit](https://pre-commit.com/) which blocks commits when style/type checks fail, but that also raises the barrier, so more long-term.

**Comment by solegalli** [comment]
@Okroshiashvili I know this is a big ask, but I'll ask anyway :)

Would you be able to help extend type_hint to the rest of the scripts? 

Should we do each of the folders discretisation, encoding, imputation, outliers and selection in a different PR? Or should we do them altogether in one?

I don't think that these folders will change much in the next months so we could do in 1 PR as well. Maybe that's best.

Thank you!

**Comment by solegalli** [comment]
Great! that's fantastic news. Thank you so much. 

Any time you can volunteer is extremely welcome. Thanks a lot.

Develop branch was merged to master, so next PR should be to master now :)

**Comment by Okroshiashvili** [comment]
@solegalli next PRs should be on the master branch?

**Comment by solegalli** [comment]
@Okroshiashvili yes please :)

**Comment by Okroshiashvili** [comment]
@solegalli I'm on my way. There will be some changes tomorrow. 

Btw, I had lots of conflicts while trying to make my fork even with the current master. I decided to remove my fork of the repo and reforked it again. I do hope my past work is not lost. :)

**Comment by solegalli** [comment]
you passed work is merged in master. So you should be able to recover it ;). I can also see you there as one of the contributors (and I already added your name in the changelog.rst in docs, for the next release), so no stresses :)

Sorry you had problems with the fork. Look forward to the changes. Have a good day!

**Comment by solegalli** [comment]
@Okroshiashvili 1 suggestion, if you don't mind, please leave reformatting the folder "selection" to the end, cause we are adding transformers there. In case it generates conflicts with other contributors. Cheers

**Comment by Okroshiashvili** [comment]
@solegalli no worries about "selection" folder. I'll put it aside. Have a nice day. :)

**Comment by Okroshiashvili** [comment]
@solegalli I'm looking at the code base and wonder if we want to standardize class docstrings? There are different styles used across modules. Do I go for it and standardize all of them? What about adopting one style of writing docstring for code?

**Comment by solegalli** [comment]
@Okroshiashvili  standarization sounds good. What do you have in mind? I like the changes you made with raises / returns in the docs you already modified. What else would you standardize? if you want, give it a go, maybe add a comment with a major re-styling so I understand what is happening. Or alternatively, we can discuss the changes you have in mind before you do a lot of work? 

what do you think?

**Comment by Okroshiashvili** [comment]
@solegalli It would be much better if we will write docstrings consistently. That means that I will modify docstring for classes as I did for methods and functions. [You can check this example](https://google.github.io/styleguide/pyguide.html#384-classes)

Will it be acceptable writing docstring for classes as I did for functions and methods?

**Comment by Okroshiashvili** [comment]
See PR #166

**Comment by Okroshiashvili** [comment]
referencing PR #166

**Comment by Okroshiashvili** [comment]
see PR #171

**Comment by solegalli** [comment]
#177 closes most of this issue. Only remains rolling out type hint in selection folder
