### ISSUE TITLE
Hybride Recursive Feature Elimination Transformer

### ISSUE THREAD

**Issue by firefly1248** [solegalli/feature_engine#156]
I want to suggest my implementation of Hybride Recursive Feature Elimination Transformer from the issue #134 . 
It also supports working with CatBoostClaaffifier and CatBoostRegressor, modern gradient boosting trees models which allows to put categorical and text features directly into model's 'fit method'.

The jupyter notebook with implementations and some examples of application could be found here
https://drive.google.com/file/d/1ArrSzNKtFsOQ_m3FgHl3v4mQMxvj-aY7/view?usp=sharing

**Comment by solegalli** [comment]
Hi @firefly1248 thanks for the suggestion. Is the code you provide in the Juypyter notebook similar to that indicated in issue #134 ?

Is this the same or a similar transformer that the one you have in mind?

If it is similar, could you make a PR referencing this and #134 issue with some initial code and we take it from there? 

If it is different, could you tell me how it is different?

thanks a lot!

**Comment by firefly1248** [comment]
Hi, @solegalli ! You are totally right! This notebook implements the same idea that you suggested in issue #134. Sorry that I didn't notice that issue. I thought that to mention your cource, where I got familiar with this idea for the first time will be enough. )

**Comment by solegalli** [comment]
great! could you give it a go, and make an initial PR with some code and we take it from there? For inspiration, check the other classes to select features that are available within the selection folder of feature-engine. And for the time being, please check out the develop branch which contains the latest version of the code, and make the PR to develop (not master).
Thanks a lot for your participation! Look forward to the PR
