### ISSUE TITLE
unify docstrings format

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#167]
Follow sklearn and imbalanced learn style

**Comment by solegalli** [comment]
Stick to Numpy style with the underline and without indentation.

At the top of the dosctrings,include **explanation**, **params**, **attributes** and **methods**, plus **examples** if any? could we add the >>> to the code examples if they are not there already?

and then the docstrings for the methods themselves, with sections **args**, **raises**, and **returns**?

**Comment by Okroshiashvili** [comment]
referencing PR #166
