### ISSUE TITLE
Giving error "ValueError: Some of the variables to transform contain missing values. Check and remove those before using this transformer"  in discretization

### ISSUE THREAD

**Issue by hrideshkohli** [solegalli/feature_engine#169]
**Describe the bug**

I added EqualFrequencyDiscretiser in a pipeline, and fit it and transformed the train data however, when transforming test data, it is giving below error:
ValueError: Some of the variables to transform contain missing values. Check and remove those before using this transformer.

I already verified that there is no null value. 
X_test.isnull().values.any() is giving FALSE

**To Reproduce**
1. Go to '...' https://github.com/hrideshkohli/Error/blob/main/end-to-end-stacking-regression-techniques-analysis.ipynb
2. Click on '....' Last cell..

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by hrideshkohli** [comment]
Additionally, i found that when using OrdinalCategoricalEncoder, the values which are not found in the train set but they are present in test site, it simply assigns NAN to those values and hence after transformation, test set contains null values

**Comment by solegalli** [comment]
Hi @hrideshkohli 

It is a known issue that labels present in the test set and not in the train set are hard to handle. The transformer did not learn a mapping for that label and thus assigns NaN.

2 ways to go about it: remove infrequent / potentially new labels with the RareLabelEncoder, or encode using OneHotEncoder of frequent categories.

Regarding the discretiser, can it be that NaN are introduced after some transformation? the transformer should work fine with datasets without NaN so not sure why it is not working in your case.

The notebook you linked has a lot of code, to be able to reproduce I would need just a snippet of code which is returning the error.

Cheers

**Comment by solegalli** [comment]
I just ran your code, the error here is because NAN are introduced into the features by the OrdinalEncoder. Then these features with NAN are taken up by the discretizer and thus, it returns an error.

The error raised is not due to a bug in Feature-engine.

We will expand functionality to make errors and warnings more helpful as per indicated in issues #294 and #295
