### ISSUE TITLE
New tranformer for square root

### ISSUE THREAD

**Issue by GabrielSGoncalves** [solegalli/feature_engine#174]
Hi Soledad,

First of all, congrats on the incredible work you've been doing for the community!
I'm finishing your course on feature engineering and started using feature_engine on my projects.

I just realized that a square root transformer is not available for the transformation module.

If you want I can implement it and submit a PR.

Att,

Gabriel

**Comment by solegalli** [comment]
Hi @GabrielSGoncalves , thank you so much for your engagement. I am really happy to hear that you found the package useful.

We can apply the root square transformation with the exponential transformer passing an exponent of 1/2.  Did you try that out?

Cheers

Sole

**Comment by GabrielSGoncalves** [comment]
That's right!

I'll try it.

Thanks
