### ISSUE TITLE
imputation: complete case analysis - drop observations with na

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#183]
We need a transformer that would drop observations from the train / test set if they have na, in any or a subset of variables, as specified by the user.

Transformer works for both categorical and numerical variables

Useful to catch errors when deployed if na values appear.

Transformer is a bit dangerous, when deployed, because it will not allow users to know when variables come with na. Need to add a warning in the docs

**Comment by pradumna123** [comment]
I would Like to work on it, Can you please assign it to me

**Comment by solegalli** [comment]
@pradumna123 you certainly can, just make a PR. But the notebooks have priority at this point. So it would be super helpful if you could start with those first.
Cheers
Sole

**Comment by pradumna123** [comment]
Can you please elaborate on this?

**Comment by solegalli** [comment]
- use pandas.dropna to drop missing values in variables
- parameters variables to allow users to select variables for imputation. If None, transformer will select all variables
- parameter missing_only to indicate if imputer should drop na in all variables, or only in those which presented na in the train set
- fit method learns the variables with na if missing_only=true, alternatively, just makes df and var checks like all other imputers
- transform method removes na from selected variables
- i am also thinking of an additional method, not sure how to call it, that when you pass the data set, instead of removing the observations with NA, returns just those (so in essence it does the opposite of transform), because this would be super useful for deployment, where we actually want to know which observations we are not scoring.

If you want to give this one a go, maybe take the AddMissingIndicator as template, and modify the code as needed.

Thanks a lot!
