### ISSUE TITLE
add jupyter notebook examples for the creation transformer

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#205]
Create a folder within the example folder, called creation. At the moment there is only one transformer in this folder, so we need only 1 notebook, for the MathematicalCombination that showcases its functionality.

**Comment by Elamraoui-Sohayb** [comment]
Hi @solegalli , i'm new to open source contributions. Can i work on this?

**Comment by solegalli** [comment]
Hi @Elamraoui-Sohayb thanks for reaching out. 

Yes, that would be actually very helpful.

The idea for this PR, is to create a folder called "creation" within the "examples" folder in the repo, where we host notebooks with demos on how to use the transformers. And there make 1 jupyter notebook, showcasing the functionality of the MathematicalCombination.

Let me know if you need anything else :)

**Comment by Elamraoui-Sohayb** [comment]
Thanks @solegalli  for the explanation.
Is it required to use the Ames House Prices dataset or can we choose different one?

**Comment by solegalli** [comment]
You can certainly use a different dataset, but there are a few conditions: the dataset needs to be part of a renown open source package, like scikit-learn, or be available with a license that states that it is free to use. So for example, most of Kaggle datasets do not qualify. But we can use most of those in the UCI machine learning repository.

For simplicity, I suggest you use one from sklearn, I tried this transformer with the cancer dataset.

Cheers
Sole
