### ISSUE TITLE
add jupyter notebook examples for the SklearnTransformerWrapper

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#206]
At the moment there is only 1 notebook showing how to wrap the one hot encoder, simple imputer and standard scaler from sklearn. I would like to separate each one of these in an individual notebook.

In addition, I would like to add notebooks demonstrating how to wrap for example the PowerTransformer, the FunctionTransformer and the Feature selection methods.

**Comment by ashok49473** [comment]
Hello @solegalli mam, 
Assign this one to me.

**Comment by solegalli** [comment]
Sure! Thank you!

**Comment by solegalli** [comment]
The idea here is to create several notebooks more or less like this:

- one notebook with imputation (simple imputer and iterative imputer)
- one notebook with some of the scalers
- one notebook with one hot encoder and ordinal encoder
- one notebook with kbinsdiscretizer
- one notebook with some of the selectors (selectKbest, selectpercentile)

Would that be ok?

**Comment by ashok49473** [comment]
Ok, I'll get started on this

**Comment by ashok49473** [comment]
Hello @solegalli mam,
SklearnTransformerWrapper is giving some error with the SelectKBest transformer.
Please help!
![Screenshot (36)](https://user-images.githubusercontent.com/73692009/111255682-8fe1d080-863d-11eb-9954-e5eb5f5a2dd0.png)

**Comment by solegalli** [comment]
can you try passing a list to the argument variables instead of X_train.columns and see if that resolves the issue? 

If not, please upload the code that is giving the error in a PR referencing this issue

thank you! @ashok49473
