### ISSUE TITLE
create notebooks with pipeline examples, within pipeline folder

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#207]
The idea here is to create several notebooks showcasing different pipelines for different datasets, to kind of provide an idea of how simple and tidy it is to use Feature-engine transformers, particularly looking forward to deployment.

**Comment by pradumna123** [comment]
Hello, Is this still available?

**Comment by solegalli** [comment]
Yes, we have PR #219 with a new pipeline for the house prices dataset, and we are looking to add more pipelines using different feature engineering techniques on different datasets. So if you have an idea of a new pipeline, please add a notebook to this PR :)))))
