### ISSUE TITLE
Major Issues Importing the Functions

### ISSUE THREAD

**Issue by katiewerner** [solegalli/feature_engine#217]
The website has changed all of the code examples.  When I have updated the installation and the code to match the examples, I get all kind of errors.   Could be user error, but I've tried all I can think of.

This (taken from the new website info):
    from feature_engine.imputation import CategoricalImputer 
Gives:
    ModuleNotFoundError:  No module named 'feature_engine.imputation'

After going and manually deleting the libraries (pip uninstall didn't really work) and reinstalling the new version, the same line of code gives this error:

  ImportError:  cannot import name '_check_input_parameter_variables' from 'feature_engine.variable_manipulation' ....

**Comment by solegalli** [comment]
did you check that you have feature_engine version 1 installed?

if you do
```
import feature_engine
feature_engine.__version__
```

what do you see? should be 1.0.0

**Comment by katiewerner** [comment]
OK, I feel like a total loser but what happened was is that I needed to shut it all down and re-open.  While I had downloaded the new version, it was confused but now seems to be pulling the correct info.  Sorry to waste your time!

**Comment by solegalli** [comment]
No problem at all! We are here to help :)

Glad you got it sorted.
