### ISSUE TITLE
Ciclycal Features.

### ISSUE THREAD

**Issue by hectorpatino** [solegalli/feature_engine#230]
Hi @solegalli, I was practicing on kaggle the cat_on_dat_II challenge and I found that some features may be ciclycal, it was the first time I read that term. So according to  [this blog](http://blog.davidkaleko.com/feature-engineering-cyclical-features.html#:~:text=Hours%20of%20the%20day%2C%20days,each%20other%20and%20not%20far.) It is a way to treat some numerical variables when the max number of a variable is close to the min number and it is a very common mistake. I checked the issues but didn´t see something related to it, so it will be nice to have that kind of transformer.
I'm not that good in programming but if you think this is worth doing I may work a while on it.

**Comment by solegalli** [comment]
Hi @hectorpatino curiously, I also saw a Kaggle notebook last week that worked with cyclical features and took a mental note to have a look at some point.

Happy for you to give it a go. I link here a couple of Kaggle notebooks for reference. Do you know of any article that discusses this encoding?

Not sure in which folder to add this transformer. I don't think it belongs to transformation, maybe a separate module? thoughts

https://www.kaggle.com/mansipriya/handling-cyclic-data?scriptVersionId=31108111

https://www.kaggle.com/danofer/cyclical-weather-features-for-deep-learning

https://www.kaggle.com/avanwyk/encoding-cyclical-features-for-deep-learning

https://datascience.stackexchange.com/questions/5990/what-is-a-good-way-to-transform-cyclic-ordinal-attributes

**Comment by hectorpatino** [comment]
Well @solegalli I haven't do a serious research about it, but I will check your links and look some academical papers. 
I think the folder should be transformation as there are Log, Reciprocal and other mathematical transformations. In this case any variable will be mapped into 2 new features being: var_sin, var_cos. So according to this, I think it is the best option.

**Comment by solegalli** [comment]
great. If you would like to give it a go, make a PR with some code and we take it from there. Probably the easiest would be to take the skeleton of the other transformers as template. Cheers
