### ISSUE TITLE
where is it in code CombineWithReferenceFeatures

### ISSUE THREAD

**Issue by Sandy4321** [solegalli/feature_engine#231]
Please let us know if you think there is information missing, or how else we can improve the documentation from Feature-engine.

where is it in code
CombineWithReferenceFeatures
as written 
New transformers
CombineWithReferenceFeatures: applies mathematical operations between a group of variables and reference variables (by Nicolas Galli)

DropMissingData: removes missing observations from a dataset (Pradumna Suryawanshi)

If you are referring to an existing page, please paste the url.
https://feature-engine.readthedocs.io/en/latest/whats_new/v1.html?highlight=CombineWithReferenceFeatures#new-transformers

**Comment by solegalli** [comment]
https://feature-engine.readthedocs.io/en/latest/creation/CombineWithReferenceFeature.html

**Comment by Sandy4321** [comment]
thanks
long time ago I asked you about many features interactions 
for example 
given 20 categorical features 
create all 
3 features interactions
sounds simple
but you still can not do it?
