### ISSUE TITLE
Is it possible to generalize PRatioEncoder as VarEncoder?

### ISSUE THREAD

**Issue by GLevV** [solegalli/feature_engine#232]
To encode categories PRE uses formula 
p(1)/p(0)
and only suitable for y~Ber (classification).

But here is an idea: variance of Bernoulli distributed X is equal p(1)*p(0), which is close and should be correlated to the first formula. Computing variance should also allow PRE to be used in regression tasks (when y is not {0,1}) and also opens door to adding options for different variance measures, like var, entropy, mad etc.

**Comment by solegalli** [comment]
Hi @GLevV thanks for the idea. 

Could you add a link to an article or blog or demo where something like this is used? or some more information about the math underlying your suggestion and why this would add value to the encoding of variables? where was this technique used?

Thank you!
