### ISSUE TITLE
add inverse_transform method to variable transformer classes

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#248]
Add to the log, power and reciprocal transformers (https://github.com/solegalli/feature_engine/tree/master/feature_engine/transformation) an inverse_transform method that performs the inverse operation. 

So for log it would be exp, for exp it would be log, for 1/x it would be 1/x

BoxCox and Yeojohnson, would continue without the inverse_transform. Not sure these operations can be reversed.

**Comment by solegalli** [comment]
closed in #283

**Comment by GiorgioSgl** [comment]
I think in yehojonson transformer it's possible to add the inverse function. 

In sklearn PowerTransformer documentation is explained in the following way:

> The inverse of the Box-Cox transformation is given by:
> 
> if lambda_ == 0:
>     X = exp(X_trans)
> else:
>     X = (X_trans * lambda_ + 1) ** (1 / lambda_)
> 
> The inverse of the Yeo-Johnson transformation is given by:
> 
> if X >= 0 and lambda_ == 0:
>     X = exp(X_trans) - 1
> elif X >= 0 and lambda_ != 0:
>     X = (X_trans * lambda_ + 1) ** (1 / lambda_) - 1
> elif X < 0 and lambda_ != 2:
>     X = 1 - (-(2 - lambda_) * X_trans + 1) ** (1 / (2 - lambda_))
> elif X < 0 and lambda_ == 2:
>     X = 1 - exp(-X_trans)

@solegalli if you tell me this is rigth, I will do a PR. 🔝

**Comment by Morgan-Sell** [comment]
Hi @GiorgioSgl, please proceed with the PR.

@solegalli is on vacation. She'll be back on July 9. Consequently, there will a delay in the code review.

Thanks for contributing to feature-engine!

**Comment by GiorgioSgl** [comment]
Ou amazing so I will follow the guide of how to contribute and go ahead with the PR!
