### ISSUE TITLE
Proposal: monotonic and user defined binning

### ISSUE THREAD

**Issue by kypexin** [solegalli/feature_engine#25]
Hi, first of all thank for the great package and all the efforts put into it.
I would like to propose additional algorithms which would in my opinion add value to the package.

1. Monotonic WoE binning. This one could be pretty useful for logistic regression problems, particularly (but not limited to) in risk scoring and fraud detection models.

2. User defined binning, where you specify bin boundaries manually. 

Basically, WoE binning algorithm has quite a few Python implementations already, and user defined binning is even more straightforward, being just a matter of couple of code lines; however, I believe it would be beneficial to have both algorithms as part of feature_engine, and especially useful to have those in form of standard transformers (in sklearn style) which will allow saving and retrieving them as preprocessing models using pickle or joblib libraries.

**Comment by solegalli** [comment]
Hello, quick question. What do you mean by Monotonic WoE binning? thanks

**Comment by kypexin** [comment]
Hi Soledad, 

By monotonic binning I mean the binning method which imposes a monotonic trend for good/bad rates per bin, which is commonly used for credit risk modelling. 

Links: 

- https://rdrr.io/cran/smbinning/man/smbinning.monotonic.html
- https://github.com/jstephenj14/Monotonic-WOE-Binning-Algorithm
- https://www.researchgate.net/publication/322520135_Monotone_optimal_binning_algorithm_for_credit_risk_modeling

**Comment by solegalli** [comment]
Hi @kypexin. First of all, thank you so much for your suggestion, and sorry it took me so long to include this issue. I have now added a discretiser that allows user inputs (UserInputDiscretiser). It is in the develop branch, and I will release the new version, later today. As for the monotonic encoding, the WoE is by default monotonic (I think this is what you meant), and the EqualWidth, EqualFrequency or UserInput discretiser, can be paired with the categorical encoders that produce monotonicity as shown in this repo: https://github.com/solegalli/packt_featureengineering_cookbook/blob/master/ch05-discretisation/Recipe-3-Discretisation-plus-categorical-encoding.ipynb
to obtain the desired effect. Cheers
