### ISSUE TITLE
The formula to calculate WoE in WoERatioCategoricalEncoder may not be correct:

### ISSUE THREAD

**Issue by xiaobenhou** [solegalli/feature_engine#26]
Hello,
Thank you for creating this package. It covers almost all the hot topics in feature engineering.
One thing I noticed that the formula to calculate WoE in WoERatioCategoricalEncoder may not be correct. The percentage of goods should be the count of goods in that category divided by the total counts of goods in the sample space, not the count of goods divided by the total counts of that category. The same calculation as percentage of bads.
for your example in the doc of WoERatioCategoricalEncoder:
the WoE for 'cabin' variable in titanic dataset should be:
{'cabin': {'B':1.629962
  'C':0.721704 ,
  'D':1.405081 ,
  'E':1.405081 ,
  'Rare': 0.738745,
  'n': -0.357528}
The calculation is below:
cabin	n_obs	prop_[1]	prop_n_obs	n_[0]	n_[1]	prop_n_[0]	prop_n_[1]	WoE_correct	WoE_in_Doc
n	702	0.304843	0.766376	488	214	0.866785	0.606232	-0.357528	-0.824339
C	71	0.56338	        0.077511	31	40	0.055062	0.113314	0.721704	0.254892
Rare	37	0.567568	0.040393	16	21	0.028419	0.05949	        0.738745	0.271934
D	32	0.71875	        0.034934	9	23	0.015986	0.065156	1.405081	0.93827
E	32	0.71875	        0.034934	9	23	0.015986	0.065156	1.405081	0.93827
B	42	0.761905	0.045852	10	32	0.017762	0.090652	1.629962	1.163151

**Comment by solegalli** [comment]
Hi @xiaobenhou 
Thanks for the heads-up. Do you have any documentation or link with the correct formula that I can attach to this issue?  could you add it to this thread please?

**Comment by xiaobenhou** [comment]
@solegalli, 
I attached one below:
https://blogs.oracle.com/r/computing-weight-of-evidence-woe-and-information-value-iv
Thank you.

**Comment by solegalli** [comment]
@xiaobenhou thank you, I will look into it. A priori, I think that modelling the prior probability to encode categories, the way it is suggested in the article, it is a bit of an overkill. 
That implementation is probably included in the package category encoders, that also allows you to select categories. Did you have a look at it?

**Comment by xiaobenhou** [comment]
@solegalli 
The blog I attached explains from a mathematical perspective on why WOE's formula is log(P(X=xj|Y = 1)/P(X=xj|Y=0)) not log(P(Y=1|X=xj)/P(Y=0|X=xj)) which is  what you used in WoERatioCategoricalEncoder.

The results based on the two calculations are very similar if your dataset is a balanced one. However, the WOE value is significantly inflated if you have an extremely unbalanced dataset. I borrowed one example from https://www.listendata.com/2015/03/weight-of-evidence-woe-and-information.html and added one additional table  for your reference:

WOE table from listendata.com:

bins | non events | events | %non events | %events | woe | %non events_1 | %events_1 | WOE_your formula

1 | 197 | 20 | 5.38% | 5.92% | -0.09525 | 90.78% | 9.22% | 2.29
2 | 450 | 34 | 12.29% | 10.06% | 0.200168 | 92.98% | 7.02% | 2.58
3 | 492 | 39 | 13.44% | 11.54% | 0.152198 | 92.66% | 7.34% | 2.53
4 | 597 | 51 | 16.30% | 15.09% | 0.077373 | 92.13% | 7.87% | 2.46
5 | 609 | 54 | 16.63% | 15.98% | 0.040115 | 91.86% | 8.14% | 2.42
6 | 582 | 55 | 15.89% | 16.27% | -0.02358 | 91.37% | 8.63% | 2.36
7 | 386 | 41 | 10.54% | 12.13% | -0.14045 | 90.40% | 9.60% | 2.24
8 | 165 | 23 | 4.51% | 6.80% | -0.41227 | 87.77% | 12.23% | 1.97
9 | 184 | 21 | 5.02% | 6.21% | -0.21231 | 89.76% | 10.24% | 2.17
  | 3662 | 338 | 

WOE table for an unbalanced dataset:

bins | non events | events | %non events | %events | woe | %non events_1 | %events_1 | WOE_your fomular

1 | 19700 | 20 | 5.38% | 5.92% | -0.09565 | 99.90% | 0.10% | 6.89
2 | 45000 | 34 | 12.29% | 10.06% | 0.200168 | 99.92% | 0.08% | 7.19
3 | 49200 | 39 | 13.44% | 11.54% | 0.152198 | 99.92% | 0.08% | 7.14
4 | 59700 | 51 | 16.30% | 15.09% | 0.077373 | 99.91% | 0.09% | 7.07
5 | 60900 | 54 | 16.63% | 15.98% | 0.040115 | 99.91% | 0.09% | 7.03
6 | 58200 | 55 | 15.89% | 16.27% | -0.02358 | 99.91% | 0.09% | 6.96
7 | 38600 | 41 | 10.54% | 12.13% | -0.14045 | 99.89% | 0.11% | 6.85
8 | 16500 | 23 | 4.51% | 6.80% | -0.41227 | 99.86% | 0.14% | 6.58
9 | 18400 | 21 | 5.02% | 6.21% | -0.21231 | 99.89% | 0.11% | 6.78
  | 366200 | 338 |   














, .

**Comment by solegalli** [comment]
Hi @xiaobenhou thank you so much for bringing this to my attention, and I am really sorry it took me so long to fix this. The update is now in the develop branch, and I will release the new version later today. Cheers!!
