### ISSUE TITLE
from feature_engine import categorical_encoders not working in Kaggle Jupyter Notebook

### ISSUE THREAD

**Issue by rohan-paul** [solegalli/feature_engine#269]
**To Reproduce**

I just have the following code in Kaggle Notebook

```py
!pip install --upgrade pip
!pip install --upgrade feature-engine

from feature_engine import categorical_encoders as ce
```

Instead of the above lines to install I also tried with `!pip install feature_engine` following [this](https://stackoverflow.com/a/63863747/1902852)

And in both cases, after running this cell getting below error.

```
ImportError: cannot import name 'categorical_encoders' from 'feature_engine' (/opt/conda/lib/python3.7/site-packages/feature_engine/__init__.py)
```

Running `!pip show feature_engine` gives below

```
Name: feature-engine
Version: 1.0.2
Summary: Feature engineering package with Scikit-learn's fit transform functionality
Home-page: http://github.com/solegalli/feature_engine
Author: Soledad Galli
Author-email: solegalli@protonmail.com
License: BSD 3 clause
Location: /opt/conda/lib/python3.7/site-packages
Requires: scipy, pandas, statsmodels, scikit-learn, numpy
Required-by: 
```

**Comment by rohan-paul** [comment]
Closing after resolving.

Basically, I had to upgrade the version of `feature_engine` with

```
$ pip install -U feature-engine
```

And now importing categorical encoders from feature_engine.encoding as below

```
from feature_engine.encoding import OneHotEncoder
```

The format below that I was using was for the older version (0.6x)

```
from feature_engine import categorical_encoders as ce
```

**Comment by solegalli** [comment]
Glad you got this sorted :)
