### ISSUE TITLE
[Feat]: Mutual Information in SmartCorrelatedSelection method

### ISSUE THREAD

**Issue by TremaMiguel** [solegalli/feature_engine#275]
**Is your feature request related to a problem? Please describe.**

Mutual Information help identifies different type of relationships between variables, not only linear relationships like Pearson or monotonic relations like spearman. 

**Describe the solution you'd like**

[SmartCorrelatedSelection](https://github.com/solegalli/feature_engine/blob/master/feature_engine/selection/smart_correlation_selection.py#L229) calls `pandas.corr()` under the hood, this method can also receives a custom function implementing calculating the mutual information between two variables, this [Stackoverflow answer](https://stackoverflow.com/questions/63969194/how-to-calculate-pairwise-mutual-information-for-entire-pandas-dataset/67987713#67987713) shows an example. 

The Mutual information can be calculated through the method `mutual_info_regression` from sklearn (its already a required dependency) or a custom calculation.

**Comment by solegalli** [comment]
This is actually and easy issue. 

We need to remove the init checks in [this line](https://github.com/solegalli/feature_engine/blob/master/feature_engine/selection/smart_correlation_selection.py#L146) for the SmartCorrelatedSelection and in [this line](https://github.com/solegalli/feature_engine/blob/master/feature_engine/selection/drop_correlated_features.py#L89) for the drop correlated features transformer and that would allow the user to pass a custom function.

We should also add 1 test for each class to make sure that it works. And finally modify the docstrings and ideally add a Jupyter notebook. So to summarize:

- [ ] remove the init checks in [this line](https://github.com/solegalli/feature_engine/blob/master/feature_engine/selection/smart_correlation_selection.py#L146) for the SmartCorrelatedSelection
- [ ] remove the init checks in [this line](https://github.com/solegalli/feature_engine/blob/master/feature_engine/selection/drop_correlated_features.py#L89) for the drop correlated features transformer
- [ ] add 1 test for each class to make sure that it can take a custom function like the mutual_info
- [ ] modify the docstrings
- [ ] modify existing jupyter notebook in /examples or make a new one to showcase the new functionality

fancy giving it a go? @TremaMiguel

**Comment by TremaMiguel** [comment]
@solegalli, would it be extending the method parameter to accept any valid callable ? 

```
method: string or callable, default='pearson'
        Can take 'pearson', 'spearman', 'kendall' or any callable method. It refers 
        to the correlation method to be used to identify the correlated features.
        - pearson : standard correlation coefficient
        - kendall : Kendall Tau correlation coefficient
        - spearman : Spearman rank correlation
        - callable: callable with input two 1d ndarrays and returning a float
```

or could it be a mutual information option in `SmartCorrelatedSelection` ? 

```
method: string, default='pearson'
        Can take 'pearson', 'spearman', 'kendall' or `mi`. It refers 
        to the correlation method to be used to identify the correlated features.
        - pearson : standard correlation coefficient
        - kendall : Kendall Tau correlation coefficient
        - spearman : Spearman rank correlation
        - mi: Mutual Information criteria.
```

in this case, the methods could be accessed from an EnumClass

```
from enum import Enum
from feature_engine.utils import mutual_information_score
 
#def mutual_information_score(x, y):
#   pass

class CorrMethods(Enum):
    pearson = 'pearson'
    kendall = 'kendall'
    spearman = 'spearman'
    mi = mutual_information_score


CorrMethods.spearman
>>> <CorrMethod.spearman: 'spearman'>
CorrMethods.mi
>>> <function mutual_information_score at 0x0000027059C8B310>
```

**Comment by solegalli** [comment]
I think that given that pandas.corr() takes any callable, let's just extend the functionality to accept any callable. No?

**Comment by TremaMiguel** [comment]
agree, this will open the possibility to other kinds of functions. To exemplify the MI method adding a Jupyter Notebook with an example would help. Thanks @solegalli

**Comment by TremaMiguel** [comment]
@solegalli , I've opened a [PR](https://github.com/solegalli/feature_engine/pull/279) solving this issue, target branch is 1.1.X, should it be pointed to master ?

**Comment by solegalli** [comment]
Yep, I saw. I am reviewing as we speak. 

We make all PR to master, and after we have a few additions, we release a new version in 1.1.x.

So in short, PRs to master :)
