### ISSUE TITLE
Allow user defined value to replace rare categories 

### ISSUE THREAD

**Issue by ofbennett** [solegalli/feature_engine#28]
Great package! Thanks for all the work put into it. 

Just a small point - In the RareLabelCategoricalEncoder I wondered if it might be nice to allow the user to define a value to replace rare categories with (but still default to 'Rare'). You could perhaps imagine someone wanting all the rare categories subsumed into an existing larger category for example.

**Comment by solegalli** [comment]
Hi Oscar,

Thanks for the feedback. Yes, this is coming in the new release of feature-engine in hopefully 2 weeks. I am aiming to do it faster.

If you find some other things that could be improved, please let me know. Anything from typos in the docs, to additional features, all helps.

Cheers
