### ISSUE TITLE
Stale link (404) to "nice summary" article

### ISSUE THREAD

**Issue by chrish42** [solegalli/feature_engine#288]
The [main page of the doc](https://feature-engine.readthedocs.io/en/1.0.x/index.html) has a link to an article that is supposed to have a "[nice summary of what is unique about Feature-Engine](https://www.trainindatablog.com/feature-engine-a-new-open-source-python-package-for-feature-engineering)"... except that link leads to a 404. 😢

**Comment by solegalli** [comment]
Thank you for the heads-up. This is [the working link](https://trainindata.medium.com/feature-engine-a-new-open-source-python-package-for-feature-engineering-29a0ab88ea7c). I will fix it and it will be available in our next release.
