### ISSUE TITLE
Discretiser - return interval boundaries

### ISSUE THREAD

**Issue by pellanda** [solegalli/feature_engine#41]
I would like to suggest discretiser had an option to return interval boundaries instead of an integer, it turns more understandable the variable content output.

for example: outputs 1, 3, 2 turns (0,10] , (20,30], (10,20]

Thanks in advance

**Comment by solegalli** [comment]
@pellanda that has been added already. If you would like to use it straightaway, clone the repo, cd into repo folder, checkout develop, and then do pip install setup.py.
Alternatively, I will probably release a new version to Pypi later next week, and you can install it from there with pip install feature-engine. Cheers.
