### ISSUE TITLE
RareLabelCategoricalEncoder checks if new data matches shape of the data it was fitted on and throws exception if they do not match

### ISSUE THREAD

**Issue by slavakx** [solegalli/feature_engine#51]
RareLabelCategoricalEncoder checks if new data matches shape of the data it was fitted on and throws exception when the number of columns do not match. 

It makes usage of the encoder in the real setup (unseen data) difficult. 

A temporal and ugly workaround is to create dummy columns just to match the number of columns in a new data. 

The desired behavior is to apply the encoder on the columns that were defined to undergo the transformation and throw exception if these columns do not exist in a new data set.

**Comment by solegalli** [comment]
Hello, thanks for raising this issue.

That check is actually a safeguard, to ensure (as much as possible) that the user is passing the same sort of dataset, aka, the same number of features, when they train the transformer with fit() and then when they transform new data with transform().

Scikit-learn transformers and predictors also check, one way or another, that the number of columns of the data set that was used to fit the transformer is the same as the one that is being used with the transform() or predict() methods. So in Feature-engine, I chose to continue with this practice.

This safeguard encourages good design of pipelines from the start, by not allowing the scoring of different data sets than those used for training the transformer,s which may lead to unintended errors or results. So, unless a lot of users complain about the safeguard, I would continue with the practices started in sklearn.

Hope this helps.

**Comment by slavakx** [comment]
Hi
thanks for your response. I don't agree with your logic. The encoder should care about the columns it transforms but not making assumptions about the overall number of columns in a dataset. 
The current functionality works fine probably because most of your users are using it in course/competition setups but it breaks the logic when it should be used in a real world setup with unseen data. 

It is really pity that I need to search for another package now...
