### ISSUE TITLE
transform the feature back to original form

### ISSUE THREAD

**Issue by Pmohan28** [solegalli/feature_engine#53]
While we use the target guided mean encoding we tend to replace the labels by its mean and fit the algo on top of it. So now if we create decision tree it will show the split of features along with its value using mean values. 
It will be better if there is inverse transform function in feature engine which can resort back to the original values of the dataframe.

Requesting for new feature addition in the feature engine library for including the inverse transform.

**Comment by solegalli** [comment]
Hi @Pmohan28 I have added the inverse_transform functionality for most categorical encoders, that is, for those where getting the original values is possible. This excludes the rarelabelencoder, and the onehotencoder.
Inverse_transform is not possible for discretisers, outlier removers and imputers. And for the variable transformers, while possible for some, I wonder if this is really useful.
The changes live in the develop branch, and will be released later today. Thank you for your participation!

**Comment by Pmohan28** [comment]
Hi Sole,
Thanks for incorporating this functionality. Is the change released now from dev branch?

**Comment by solegalli** [comment]
Yes, it was released last Friday.
