### ISSUE TITLE
improve imputation notebooks

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#58]
Separate each missing data imputer into a single notebook, within the imputer folder. Check if new parameters or changes have been done to the imputers, and try to include a demo in the notebook.

**Comment by pradumna123** [comment]
Can you assign this to me ?

**Comment by solegalli** [comment]
Hi @pradumna123 thanks for your support. I saw that you left messages in 3 different issues. Maybe we can start by this one? 

We are soon to launch a new release of feature-engine, and we changed a bit the way we do the imports and also the parameter names of some of the imputers.

So the idea for this issue, is to:
- separate each imputer in a different notebook which would take the imputer's name
- try and show case all the functionality of each transformer, for example for the MeanMedianImputer, imputation by the mean, and median, and how the user can assign variables or alternatively let the imputer find them automatically.
- fix the imports: now if would be from feature_engine.imputation instead of how it is in the notebook
- make sure the parameters have the latest names.

In order for this to work, as we have not released the latest version yet, we need to install feature engine in developer mode, you can find instructions here:
https://feature-engine.readthedocs.io/en/latest/contributing/github_quick_start.html

If you are interested, just make a new PR with the initial changes and we take it from there.

Cheers!

**Comment by pradumna123** [comment]
So we will have a file for every imputer.
 Do we have a list of all such imputers.
The documentation shows 6. If I am not wrong

**Comment by solegalli** [comment]
https://github.com/solegalli/feature_engine/blob/master/feature_engine/imputation/__init__.py

**Comment by pradumna123** [comment]
Cool thank you

**Comment by solegalli** [comment]
If you enter into each imputer .py file, you will see the docstrings with the new information (if anything changed). Thanks a lot!

**Comment by solegalli** [comment]
closed in #209
