### ISSUE TITLE
improve categorical encoding notebooks

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#59]
Separate each categorical encoder into a single notebook, within the encoders folder. 

Check, if new parameters or functionality has been added and include examples within the notebooks.

**Comment by solegalli** [comment]
@NicoGalli este es para modificar los notebooks existentes. Hay que hacer un notebook por transformador (al momento estan todos los transformadores en un notebook solo).

Simple

**Comment by ashok49473** [comment]
Hello @solegalli 
would you please assign this one to me?

**Comment by solegalli** [comment]
Hi @ashok49473 yes, that would be great. 

Note that in master we have the latest version of the package that we have not yet released. So the notebooks should be improved / updated with that version.

You will need to clone the repo and install the package in developer mode:
https://feature-engine.readthedocs.io/en/latest/contributing/github_quick_start.html

**Comment by solegalli** [comment]
worked done here #193
