### ISSUE TITLE
DecisionTreeDiscretiser what page to read from CiML-v3-book.pdf

### ISSUE THREAD

**Issue by Sandy4321** [solegalli/feature_engine#6]
may you clarify what page from http://www.mtome.com/Publications/CiML/CiML-v3-book.pdf is relevant to read about 
https://feature-engine.readthedocs.io/en/latest/discretisers/DecisionTreeDiscretiser.html?highlight=DecisionTreeDiscretiser
as you wrote
The methods is inspired by the following article from the winners of the KDD 2009 competition:

http://www.mtome.com/Publications/CiML/CiML-v3-book.pdf

but there are 130 pages..

**Comment by solegalli** [comment]
Page 27, "Features from tree induction". However, there is a lot of useful and interesting content in those articles, so I recommend reading the entire book, or at least the first 4 articles. Cheers
