### ISSUE TITLE
improve outlier jupyter demos

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#61]
Demonstrate each class into a single jupyter notebook (at the moment all classes are together in 1 notebook)

Check if new functionality has been added, and include a demonstration in the notebook.

**Comment by mobin102** [comment]
Hello @solegalli 
Can I work on this one?

**Comment by solegalli** [comment]
You certainly can @mobin102 

We need to use datasets that have an open source license (free to use, share and modify even commercially). 

We should not upload a csv file with data to the repo. Maybe it is a good solution, as much as possible, to use the datasets that already come baked into sklearn and imbalanced-learn. If not possible, add in the notebook, guidelines for the user to download the data (i.e., where is it? UCI website? KDD website? etc)

It would be great if we could include some plots, to help users understand what the transformer is doing, and how the transformation alters the data.

Thanks a lot for the enthusiasm.

Cheers
Sole

**Comment by mobin102** [comment]
Thanks. I'll get started on this.

**Comment by solegalli** [comment]
@ashok49473 wondered if you would be interested in picking this one up?

Apart from separating the transformers into individual notebooks, we need to add a notebook for the outlier trimmer, which is new.

**Comment by ashok49473** [comment]
hello @solegalli mam, 
Is this still available? I want to work on this one.

**Comment by solegalli** [comment]
go for it @ashok49473

**Comment by ashok49473** [comment]
I guess Winsorizer and OutlierTrimmer have the same functionality.

**Comment by solegalli** [comment]
they don't. I added a note on this in the PR review. Thank you!

**Comment by solegalli** [comment]
resolved by @ashok49473 in #235
