### ISSUE TITLE
improve variable transformers jupyter notebooks

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#62]
Separate each transformer into a new jupyter notebook. 

Check if new functionality has been added and include it in the notebook.

**Comment by pradumna123** [comment]
Can you please elaborate on this?
Is there anything specific you want to be added?

**Comment by solegalli** [comment]
@pradumna123 

We are soon to launch a new release of feature-engine, and we changed a bit the way we do the imports.

So the idea for this issue, is to:

 - separate each transformer in a different notebook which would take thetransformer's name
 -  try and show case all the functionality of each transformer, for example for the LofTransformer, transform by natural log and log 10.
 - fix the imports: now if would be from feature_engine.transformation instead of how it is in the notebook

In order for this to work, as we have not released the latest version yet, we need to install feature engine in developer mode, you can find instructions here:
https://feature-engine.readthedocs.io/en/latest/contributing/github_quick_start.html

If you are interested, just make a new PR with the initial changes and we take it from there.

Cheers!

**Comment by solegalli** [comment]
@pradumna123 wondered if you could pick this one up? that would be great help :)

**Comment by pradumna123** [comment]
Give me a few days will finish it

**Comment by pradumna123** [comment]
we are talking about boxcox, log, etc transformers, right?

**Comment by solegalli** [comment]
yes, those ones :)
