### ISSUE TITLE
encode categorical variables with trees

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#66]
Add encder to replace labels directly by the output of a decision tree.

**Comment by SuryaThiru** [comment]
Hi! I'm curious as to how this works. Can you point me to some relevant resources?

**Comment by solegalli** [comment]
The method was used for a KDD competition and is described in this series of articles:
http://www.mtome.com/Publications/CiML/CiML-v3-book.pdf

In particular, article starting on page 21, and the method is described on page 27.

This method is implemented already in Feauture-engine for numerical variables, in the discretisation transformers:
https://github.com/solegalli/feature_engine/blob/master/feature_engine/discretisers.py#L276

To extend this to categorical variables, I think the solution is straightforward, we would need to first transform the categories into numbers, I think arbitrary encoding should work just fine. And then, at the back of it, apply the decision tree as I do with numerical variables in the bit of code from discretisers.

We could even provide the option to transform categories into numbers arbitratily or following the target mean, so we could use the ordinal categorical encoder first:
https://github.com/solegalli/feature_engine/blob/master/feature_engine/categorical_encoders.py#L128

and then add a bit of code to add the decision tree layer to the encoding.

Would you be up for this? if yes, please let me know before starting with the code, because I was advised to re-organise the code a bit into smaller chunks, so this might be a good opportunity to start.

Thank you for the engagement!

**Comment by SuryaThiru** [comment]
Yes, I can work on this.

**Comment by SuryaThiru** [comment]
> 
> Would you be up for this? if yes, please let me know before starting with the code, because I was advised to re-organise the code a bit into smaller chunks, so this might be a good opportunity to start.
> 

Are you planning to refactor the library a bit before any further additions?

**Comment by solegalli** [comment]
@SuryaThiru please ignore what I said. I will make refactor as part of a big PR later in the year or in 2021. Let's continue as always. Cheers. Sole

**Comment by solegalli** [comment]
#98
