### ISSUE TITLE
feature creation: add feature combination by substraction

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#68]
https://github.com/solegalli/packt_featureengineering_cookbook/blob/master/ch09-mathematical-transformations/Recipe2-Substraction-Quotient-Features.ipynb

**Comment by pradumna123** [comment]
Can you please elaborate on the line add feature combination by substraction?

**Comment by solegalli** [comment]
Transformer should be able to take a group of variables and subtract a reference variable, or divide them by a reference variable as shown in the code linked in the issue.

Also worth thinking which additional pandas binary methods should be supported:
https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#binary-operator-functions

**Comment by pradumna123** [comment]
Thank you for the explanation will start working on it

**Comment by NicoGalli** [comment]
@solegalli would you please assign this one to me?
Thanks,
N.-

**Comment by solegalli** [comment]
assigned :p

**Comment by pradumna123** [comment]
Is this still open?

**Comment by solegalli** [comment]
it is still open.

@NicoGalli was planning to work on it. @pradumna123 you are welcome to make a contribution, you can work on it together.

Cheers

**Comment by NicoGalli** [comment]
Just a head ups. The transformer is finished. I am starting to work on testing cases this weekend.

**Comment by pradumna123** [comment]
Thank you for the update
