### ISSUE TITLE
add feature combination by math operations

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#69]
https://github.com/solegalli/packt_featureengineering_cookbook/blob/master/ch09-mathematical-transformations/Recipe1-Add-Multiply-Features.ipynb

**Comment by michalgromiec** [comment]
@solegalli If it's possible, I can take this one. I am planning to allow user to pass math operation as a list in parameter or calculate all methods from above Jupyter if parameter will be None.
