### ISSUE TITLE
add transformer that removes features from the dataset

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#70]
This is useful when we have a feature that we use to create intermediate features, like date of birth, but that we do not want among our predictors. Useful to accomodate the dataset in the sklearn pipeline

**Comment by KarthikKothareddy** [comment]
Hello @solegalli, in most of my ML projects I found that transformers for feature selectors / feature eliminators makes integration with sklearn pipelines very handy and I would like to work on this enhancement.

**Comment by solegalli** [comment]
Hi @KarthikKothareddy the transformer that I am thinking for this issue, is one that allows the user to indicate a list of features they wish to remove from the data set.

The code for the transformer is this:
https://github.com/trainindata/testing-and-monitoring-ml-deployments/blob/master/packages/gradient_boosting_model/gradient_boosting_model/processing/preprocessors.py#L64

We need to expand that code with docstrings. You can find how the docstrings look like in any of the other Feature-engine transformers. 

Because this is a new feature that adds functionality at the moment not present in Feature-engine we need to create the code, the tests and the additional documentation for sphinx. So all of the below is necessary:

- [ ] add a python script called `feature_selection.py`
- [ ] in `feature_selection.py` add the transformer with the code that I show earlier in this message + docstrings
- [ ] add a test file called `test_feature_selection.py` inside the test folder with extensive testing of the functionality of this transformer
- [ ] inside the folder docs make a subfolder called selection
- [ ] inside the selection folder we need an` index.rst` and another rst file with the name of the transformer where we add details to populate the dosctring of the transformer you create to sphinx, plus an example of how it can be used (code)

in the doc/index.rst we need to update the index so it includes the below:

- [ ] Add the feature selection functionality under the Wrappers with the transformer you create
- [ ] Add the selection folder to the toctree at the end.

In addition, a nice to have would be a Jupyter notebook in the example folder of the repo with code on how to use the transformer.

Things to be mindful of, for the test, it is better to use hard coded dataframes like the ones in the conf file inside the tests. If necessary add a new toy dataframe.

For the examples in the docstrings or jupyter notebook we need to use open source, publicily available datasets, and not data that does not have a license that clearly states that it is ok to use them.

Would you be up for it? If yes, create empty files and folders with the names that I indicate here, and make an initial PR, and we take it from there.

Remember to work from your fork, on a branch with a name that clearly indicates this issue or feature that you want to add. Thanks a lot for your engagement!

**Comment by KarthikKothareddy** [comment]
Hello @solegalli absolutely, I will start forking a separate enhancement branch and follow the steps this evening.
