### ISSUE TITLE
add feature selection methods

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#71]
as per my course feature selection for machine learning. Please get in touch for details

**Comment by KarthikKothareddy** [comment]
Hello @solegalli, I was going through your repo (as I am a student of your Feature Engineering and Feature Selection courses) and came across this ope issue. I will be more than happy to understand the requirements here and contribute as well.

**Comment by KarthikKothareddy** [comment]
Also as an addition to the above I felt like a wrapper around sklearn's FeatureUnion to output a dataframe with combining features very helpful.

**Comment by solegalli** [comment]
Hi @KarthikKothareddy. This one is actually quite a big change. Give me a few days to gather all the code that needs to be part of this change, and maybe we need to create multiple issues from this single one. And meanwhile we can work on the other issue you put your name down to?

**Comment by solegalli** [comment]
Expanded this mega issue into individual issues with the specific transformers that we should add to the package. So I will close this issue now. #114 #134 #135 #136 #137 #138
