### ISSUE TITLE
arbitrary value imputer: allow imputation with different numbers in 1 imputer

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#72]
Allow user to enter a dictionary with the values to use to replace the different variables

**Comment by michalgromiec** [comment]
I could get on with this - do we want to allow entering dictionary instead of current parameters? or both options should be possible?

**Comment by solegalli** [comment]
Hi @michalgromiec thank you so much! 

I think it would be best to allow both options. So we don't disrupt current functionality (i.e., the transformer remains backwards compatible).

**Comment by michalgromiec** [comment]
@solegalli I've developed this feature and pushed changes in PR #83
