### ISSUE TITLE
CategoricalVariableImputer

### ISSUE THREAD

**Issue by solegalli** [solegalli/feature_engine#73]
Allow user to select the string with which to replace missing data. At the moment, the only value allowed is the default one == 'missing'

**Comment by GLevV** [comment]
I rewrite code to allow custom string for imputation, and also we can modify mode imputer for case of multiple modes: we can uniformly randomly choose mode for every nan. It will save the frequencies of modes but transform method should be redefined

**Comment by solegalli** [comment]
Hi @GLevV thanks for getting in touch, and sorry for the late response, I took a few days off :) 

Would you like to modify the transformer to allow the user to input the string they wish for the imputation? If yes, could you make a feature branch with the name of this issue and make a PR to master with your changes? It would be great if you can also add a test to check that your modification works, and then update the version before we merge the PR. But let's take it one step at the time and start with the class modification and the test?

For the bimodal imputation, if you would like this addition, could you create a separate issue, and add some evidence as to when and how often this imputation is / could be used?

Cheers
Sole
